import { Effect } from "effect";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import { WorktreeError } from "./errors.js";
import * as WorktreeManager from "./WorktreeManager.js";

/**
 * Run-scoped worktree ownership receipts (issue: "prove qualification and
 * cleanup cannot mutate remote Git or contaminate worktrees").
 *
 * A receipt is created by the same run that created the worktree and binds
 * cleanup authority to stable facts — canonical path, repo identity, branch,
 * and a random token — rather than a naming convention. Destructive cleanup
 * (`WorktreeManager.remove`) refuses to act unless the worktree's freshly
 * re-read state still matches every fact on the receipt. Any mismatch or
 * unreadable state fails closed: nothing is mutated and the caller gets an
 * actionable error.
 */

/** A creation receipt proving a run owns a specific worktree. */
export interface WorktreeOwnershipReceipt {
  /** Canonical (realpath-resolved) worktree path at creation time. */
  readonly canonicalPath: string;
  /** Canonical host repo directory the worktree belongs to. */
  readonly canonicalRepoDir: string;
  /** Branch the worktree was created on. */
  readonly branch: string;
  /** Random token generated by the same run that created the worktree. */
  readonly token: string;
}

/**
 * Host-owned registry of receipts issued by runs in this process.
 *
 * This is what makes the token authority rather than decoration: a receipt
 * only authorizes destructive cleanup if its token was issued by
 * `issueReceipt` in this process AND every fact on the receipt matches the
 * registered copy. A fabricated receipt — correct path/repo/branch, arbitrary
 * token — is rejected because no run ever issued that token. The registry
 * lives in host memory, is not derivable from external git/filesystem state,
 * and dies with the process.
 */
const receiptRegistry = new Map<string, WorktreeOwnershipReceipt>();

/** Issue a receipt for a worktree this run just created and register it. */
export const issueReceipt = (input: {
  readonly worktreePath: string;
  readonly repoDir: string;
  readonly branch: string;
}): Effect.Effect<WorktreeOwnershipReceipt, WorktreeError> =>
  Effect.gen(function* () {
    const receipt: WorktreeOwnershipReceipt = {
      canonicalPath: yield* canonicalize(input.worktreePath),
      canonicalRepoDir: yield* canonicalize(input.repoDir),
      branch: input.branch,
      token: randomBytes(16).toString("hex"),
    };
    receiptRegistry.set(receipt.token, receipt);
    return receipt;
  });

/**
 * Validate a receipt's token against the run-owned registry and confirm every
 * fact matches the registered copy. Fails closed for fabricated, stale, or
 * tampered receipts.
 */
const validateAgainstRegistry = (
  receipt: WorktreeOwnershipReceipt,
): Effect.Effect<void, WorktreeError> =>
  Effect.gen(function* () {
    const registered = receiptRegistry.get(receipt.token);
    if (registered === undefined) {
      return yield* failClosed(
        receipt,
        `receipt token was not issued by any run in this process — the receipt is fabricated, revoked, or from a dead process`,
      );
    }
    if (
      registered.canonicalPath !== receipt.canonicalPath ||
      registered.canonicalRepoDir !== receipt.canonicalRepoDir ||
      registered.branch !== receipt.branch
    ) {
      return yield* failClosed(
        receipt,
        `receipt facts do not match the registered issuance record — the receipt has been tampered with`,
      );
    }
  });

/**
 * Revoke a receipt's token after terminal cleanup (removed or preserved).
 * A revoked token can never authorize another destructive mutation — closing
 * the replay edge where a same-path/same-branch worktree recreated later in
 * the same long-running process could be deleted with a stale receipt.
 */
const revokeReceipt = (receipt: WorktreeOwnershipReceipt): void => {
  receiptRegistry.delete(receipt.token);
};

const canonicalize = (p: string): Effect.Effect<string, WorktreeError> =>
  Effect.tryPromise({
    try: async () => {
      const { realpath } = await import("node:fs/promises");
      return await realpath(p);
    },
    catch: (e) =>
      new WorktreeError({
        message: `Failed to canonicalize path for ownership receipt: ${e instanceof Error ? e.message : String(e)}`,
      }),
  });

/**
 * Verify a receipt against freshly re-read external state immediately before
 * a destructive mutation. Fails closed on any mismatch, missing worktree, or
 * unreadable state — the caller must not proceed with cleanup.
 */
export const verifyOwnership = (
  receipt: WorktreeOwnershipReceipt,
): Effect.Effect<void, WorktreeError> =>
  Effect.gen(function* () {
    // Fresh read #0: the token must have been issued by a run in this
    // process and every fact must match the registered copy. This is the
    // unforgeable ownership boundary — external state alone cannot
    // authorize cleanup.
    yield* validateAgainstRegistry(receipt);

    // Fresh read #1: the worktree must still be registered in git at the
    // exact canonical path recorded at creation time.
    const registered = yield* findRegisteredWorktree(
      receipt.canonicalRepoDir,
      receipt.canonicalPath,
    );
    if (registered === undefined) {
      return yield* failClosed(
        receipt,
        `worktree is no longer registered in git at ${receipt.canonicalPath}`,
      );
    }

    // Fresh read #2: the registered worktree must still be on the branch
    // recorded at creation time. A detached HEAD or moved branch means the
    // state has changed since the receipt was issued.
    if (registered.branch !== receipt.branch) {
      return yield* failClosed(
        receipt,
        `worktree branch moved: receipt says '${receipt.branch}', git reports '${registered.branch ?? "(detached)"}'`,
      );
    }

    // Fresh read #3: the directory must still exist on disk. A vanished
    // directory with live git metadata is ambiguous — refuse to guess.
    const exists = yield* Effect.promise(async () => {
      try {
        const { stat } = await import("node:fs/promises");
        const s = await stat(receipt.canonicalPath);
        return s.isDirectory();
      } catch {
        return false;
      }
    });
    if (!exists) {
      return yield* failClosed(
        receipt,
        `worktree directory is missing at ${receipt.canonicalPath}`,
      );
    }
  });

const failClosed = (
  receipt: WorktreeOwnershipReceipt,
  reason: string,
): Effect.Effect<never, WorktreeError> =>
  Effect.fail(
    new WorktreeError({
      message:
        `Refusing destructive cleanup — ownership verification failed for worktree at ${receipt.canonicalPath} ` +
        `(branch '${receipt.branch}', receipt token ${receipt.token.slice(0, 8)}…): ${reason}. ` +
        `No mutation was performed. Inspect the worktree manually before cleaning up.`,
    }),
  );

const findRegisteredWorktree = (
  repoDir: string,
  canonicalPath: string,
): Effect.Effect<WorktreeManager.WorktreeEntry | undefined, WorktreeError> =>
  Effect.gen(function* () {
    const list = yield* Effect.tryPromise({
      try: async () => {
        const { execFile } = await import("node:child_process");
        const { promisify } = await import("node:util");
        const { stdout } = await promisify(execFile)(
          "git",
          ["worktree", "list", "--porcelain"],
          { cwd: repoDir, env: { ...process.env, LC_ALL: "C" } },
        );
        return stdout;
      },
      catch: (e) =>
        new WorktreeError({
          message: `Failed to list worktrees for ownership verification: ${e instanceof Error ? e.message : String(e)}`,
        }),
    });
    const entries: WorktreeManager.WorktreeEntry[] = [];
    let currentPath: string | null = null;
    let currentBranch: string | null = null;
    for (const line of list.split("\n")) {
      if (line.startsWith("worktree ")) {
        if (currentPath !== null) {
          entries.push({ path: currentPath, branch: currentBranch });
        }
        currentPath = line.slice("worktree ".length).trim();
        currentBranch = null;
      } else if (line.startsWith("branch ")) {
        currentBranch = line.slice("branch refs/heads/".length).trim();
      }
    }
    if (currentPath !== null) {
      entries.push({ path: currentPath, branch: currentBranch });
    }
    return entries.find((e) => e.path === canonicalPath);
  });

/**
 * Guarded destructive cleanup: verify ownership, verify the worktree holds no
 * uncommitted work (interrupted runs must be preserved, never deleted), then
 * remove the worktree, then freshly re-read state to confirm the removal
 * actually happened. Read-after-write: a successful exit code alone is not
 * proof.
 */
export const removeVerified = (
  receipt: WorktreeOwnershipReceipt,
): Effect.Effect<void, WorktreeError> =>
  Effect.gen(function* () {
    yield* verifyOwnership(receipt);

    // Fresh read #4: uncommitted work check immediately before deletion.
    // Committed or uncommitted agent work in an owned worktree is preserved
    // for human inspection — cleanup never destroys it.
    const dirty = yield* WorktreeManager.hasUncommittedChanges(
      receipt.canonicalPath,
    ).pipe(Effect.catchAll(() => Effect.succeed(true)));
    if (dirty) {
      // Terminal outcome: preserved. Revoke the token so this receipt can
      // never authorize another destructive mutation.
      revokeReceipt(receipt);
      return yield* failClosed(
        receipt,
        `worktree has uncommitted changes — preserving for inspection`,
      );
    }

    yield* WorktreeManager.remove(receipt.canonicalPath);
    // Read-after-write: the worktree must no longer be registered. If git
    // cannot tell us (list fails), state is UNKNOWN — fail closed rather
    // than interpreting the failure as absence.
    const postState = yield* Effect.either(
      findRegisteredWorktree(receipt.canonicalRepoDir, receipt.canonicalPath),
    );
    if (postState._tag === "Left") {
      return yield* Effect.fail(
        new WorktreeError({
          message:
            `Cleanup postcondition UNKNOWN: failed to re-read worktree registry after removing ${receipt.canonicalPath} ` +
            `(${postState.left.message}). External state is uncertain — inspect manually before retrying.`,
        }),
      );
    }
    if (postState.right !== undefined) {
      return yield* Effect.fail(
        new WorktreeError({
          message:
            `Cleanup postcondition failed: worktree at ${receipt.canonicalPath} is still registered in git after removal. ` +
            `External state is uncertain — inspect manually before retrying.`,
        }),
      );
    }
    // Also confirm the directory is actually gone — `git worktree remove`
    // exiting 0 is not proof on its own.
    const dirGone = yield* Effect.promise(async () => {
      try {
        const { stat } = await import("node:fs/promises");
        await stat(receipt.canonicalPath);
        return false;
      } catch {
        return true;
      }
    });
    if (!dirGone) {
      return yield* Effect.fail(
        new WorktreeError({
          message:
            `Cleanup postcondition failed: directory at ${receipt.canonicalPath} still exists after removal. ` +
            `External state is uncertain — inspect manually before retrying.`,
        }),
      );
    }
    // Terminal outcome: verified removal. Revoke the token — the worktree is
    // gone and this receipt must never authorize anything again.
    revokeReceipt(receipt);
  });

/**
 * Whether a path is inside the managed `.sandcastle/worktrees/` directory of
 * `repoDir`. Used as an additional structural guard so cleanup can never
 * target the caller's working tree or a sibling worktree outside the managed
 * directory, even if a receipt were somehow forged for it.
 */
export const isInsideManagedWorktreesDir = (
  repoDir: string,
  worktreePath: string,
): boolean =>
  WorktreeManager.isManagedWorktreePath(
    worktreePath,
    join(repoDir, ".sandcastle", "worktrees"),
  );
